name: Build and Deploy Julia Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        julia-version: 1.8
    - name: Install dependencies
      run: julia -e 'using Pkg; Pkg.add(["Documenter", "DocStringExtensions"])'
    - name: Build docs
      run: julia --project=. docs/make.jl

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: docs
    - name: Deploy docs
      run: |
        cd docs
        rm -rf ./*
        cp -r ../docs/* .
        git add .
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Update documentation"
        git push origin gh-pages
